# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 83f3ec4f67cc6092e90e72aaa9f9c0c86c397611fc6bba08da84abfe231f760a213fd67dab51c93e9a0a0e02bc4bf7664e6c6df6033395b490bedd55a8612715

test:
  secret_key_base: eda112d6fc080c638d0a21f72754caed9a4f39be7137b5e6c94b79cd723a67bed32b0e71a13eabebd821f4479d6f87e142d084e96bddd4c03a4fa7922d660703

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
